# Supply Chain Data Generation
This notebook generates all dimension and fact tables for the supply chain database.

In [2]:
import pandas as pd
import numpy as np
import random
import os
from datetime import datetime, timedelta

random.seed(42)
np.random.seed(42)

os.makedirs('data', exist_ok=True)

## Dimension Tables

In [3]:
# ── dim_date ────
start_date = datetime(2019, 1, 1)
end_date   = datetime(2024, 12, 31)

date_range = pd.date_range(start=start_date, end=end_date, freq='D')

dim_date = pd.DataFrame({
    'date_key'   : range(1, len(date_range) + 1),
    'date'       : date_range,
    'year'       : date_range.year,
    'quarter'    : date_range.quarter,
    'month'      : date_range.month,
    'month_name' : date_range.strftime('%B'),
    'week'       : date_range.isocalendar().week.astype(int),
    'day'        : date_range.day,
    'day_of_week': date_range.dayofweek,
    'day_name'   : date_range.strftime('%A'),
    'is_weekend' : date_range.dayofweek >= 5
})

dim_date['date'] = dim_date['date'].dt.strftime('%Y-%m-%d')

dim_date.to_csv('data/dim_date.csv', index=False)
print('dim_date:', dim_date.shape)
dim_date.head(3)

dim_date: (2192, 11)

,date_key,date,year,quarter,month,month_name,week,day,day_of_week,day_name,is_weekend
2019-01-01,1,2019-01-01,2019,1,1,January,1,1,1,Tuesday,False
2019-01-02,2,2019-01-02,2019,1,1,January,1,2,2,Wednesday,False
2019-01-03,3,2019-01-03,2019,1,1,January,1,3,3,Thursday,False

In [4]:
# ── dim_customer ────
dim_customer = pd.DataFrame({
    'customer_id'       : range(1, 6),
    'customer_key'      : ['CUST-001', 'CUST-002', 'CUST-003', 'CUST-004', 'CUST-005'],
    'customer_name'     : ['TechMart Global', 'RetailHub Inc', 'MegaStore Co', 'QuickShop Ltd', 'ValueChain Corp'],
    'country'           : ['USA', 'Germany', 'UK', 'Canada', 'Australia'],
    'channel_type'      : ['Online', 'Retail', 'Wholesale', 'Online', 'Retail'],
    'size'              : ['Large', 'Medium', 'Large', 'Small', 'Medium'],
    'annual_volume_usd' : [5200000, 1800000, 7500000, 450000, 2100000]
})

dim_customer.to_csv('data/dim_customer.csv', index=False)
print('dim_customer:', dim_customer.shape)
dim_customer

dim_customer: (5, 7)

,customer_id,customer_key,customer_name,country,channel_type,size,annual_volume_usd
0,1,CUST-001,TechMart Global,USA,Online,Large,5200000
1,2,CUST-002,RetailHub Inc,Germany,Retail,Medium,1800000
2,3,CUST-003,MegaStore Co,UK,Wholesale,Large,7500000
3,4,CUST-004,QuickShop Ltd,Canada,Online,Small,450000
4,5,CUST-005,ValueChain Corp,Australia,Retail,Medium,2100000

In [5]:
# ── dim_supplier ────
dim_supplier = pd.DataFrame({
    'supplier_id'      : range(1, 11),
    'supplier_key'     : [f'SUP-{str(i).zfill(3)}' for i in range(1, 11)],
    'supplier_name'    : [
        'AlphaRaw Materials', 'BetaComponents Inc', 'GammaSupply Co',
        'DeltaParts Ltd', 'EpsilonGoods Corp', 'ZetaSource LLC',
        'EtaIndustries', 'ThetaLogistics', 'IotaVendors Inc', 'KappaTraders'
    ],
    'country'          : ['China', 'USA', 'Germany', 'Japan', 'India', 'Mexico', 'South Korea', 'Taiwan', 'Brazil', 'UK'],
    'city'             : ['Shanghai', 'Chicago', 'Munich', 'Tokyo', 'Mumbai', 'Monterrey', 'Seoul', 'Taipei', 'Sao Paulo', 'London'],
    'specialty'        : ['Electronics', 'Plastics', 'Metals', 'Precision Parts', 'Textiles', 'Packaging', 'Semiconductors', 'PCB', 'Raw Materials', 'Chemicals'],
    'tier'             : [1, 2, 1, 1, 3, 2, 1, 2, 3, 2],
    'avg_quality_score': [4.5, 3.8, 4.2, 4.7, 3.5, 3.9, 4.6, 4.1, 3.3, 4.0]
})

dim_supplier.to_csv('data/dim_supplier.csv', index=False)
print('dim_supplier:', dim_supplier.shape)
dim_supplier

dim_supplier: (10, 8)

,supplier_id,supplier_key,supplier_name,country,city,specialty,tier,avg_quality_score
0,1,SUP-001,AlphaRaw Materials,China,Shanghai,Electronics,1,4.5
1,2,SUP-002,BetaComponents Inc,USA,Chicago,Plastics,2,3.8
2,3,SUP-003,GammaSupply Co,Germany,Munich,Metals,1,4.2
3,4,SUP-004,DeltaParts Ltd,Japan,Tokyo,Precision Parts,1,4.7
4,5,SUP-005,EpsilonGoods Corp,India,Mumbai,Textiles,3,3.5
5,6,SUP-006,ZetaSource LLC,Mexico,Monterrey,Packaging,2,3.9
6,7,SUP-007,EtaIndustries,South Korea,Seoul,Semiconductors,1,4.6
7,8,SUP-008,ThetaLogistics,Taiwan,Taipei,PCB,2,4.1
8,9,SUP-009,IotaVendors Inc,Brazil,Sao Paulo,Raw Materials,3,3.3
9,10,SUP-010,KappaTraders,UK,London,Chemicals,2,4.0

In [6]:
# ── dim_facility ───────────────────────────────────────────────────────────────
dim_facility = pd.DataFrame({
    'facility_id'     : range(1, 6),
    'facility_key'    : [f'FAC-{str(i).zfill(3)}' for i in range(1, 6)],
    'facility_name'   : ['North Plant', 'South Distribution', 'East Warehouse', 'West Assembly', 'Central Hub'],
    'country'         : ['USA', 'USA', 'Canada', 'Mexico', 'USA'],
    'city'            : ['Detroit', 'Atlanta', 'Toronto', 'Monterrey', 'Chicago'],
    'facility_type'   : ['Manufacturing', 'Distribution', 'Warehouse', 'Assembly', 'Distribution'],
    'specialization'  : ['Heavy Equipment', 'Consumer Goods', 'Cold Storage', 'Electronics', 'General'],
    'annual_capacity' : [120000, 95000, 60000, 80000, 150000]
})

dim_facility.to_csv('data/dim_facility.csv', index=False)
print('dim_facility:', dim_facility.shape)
dim_facility

dim_facility: (5, 8)

,facility_id,facility_key,facility_name,country,city,facility_type,specialization,annual_capacity
0,1,FAC-001,North Plant,USA,Detroit,Manufacturing,Heavy Equipment,120000
1,2,FAC-002,South Distribution,USA,Atlanta,Distribution,Consumer Goods,95000
2,3,FAC-003,East Warehouse,Canada,Toronto,Warehouse,Cold Storage,60000
3,4,FAC-004,West Assembly,Mexico,Monterrey,Assembly,Electronics,80000
4,5,FAC-005,Central Hub,USA,Chicago,Distribution,General,150000

In [7]:
# ── dim_product ────────────────────────────────────────────────────────────────
categories  = ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics',
                'Furniture',   'Furniture',   'Furniture',   'Furniture',
                'Apparel',     'Apparel',     'Apparel',     'Apparel',
                'Tools',       'Tools',       'Tools',
                'Home Goods',  'Home Goods',  'Home Goods',  'Home Goods']

product_lines = ['Consumer Tech', 'Consumer Tech', 'Consumer Tech', 'Professional', 'Professional',
                  'Office',        'Office',        'Home',          'Home',
                  'Casual',        'Casual',        'Sport',         'Sport',
                  'Power Tools',   'Power Tools',   'Hand Tools',
                  'Kitchen',       'Kitchen',       'Bedroom',       'Bedroom']

product_names = [
    'Laptop Pro 15', 'Wireless Mouse', 'Mechanical Keyboard', 'Monitor 27"', '4K Webcam',
    'Ergonomic Chair', 'Standing Desk', 'Bookshelf Unit', 'Coffee Table',
    'Casual T-Shirt', 'Denim Jacket', 'Running Shoes', 'Sport Leggings',
    'Cordless Drill', 'Circular Saw', 'Wrench Set',
    'Non-Stick Pan', 'Blender Pro', 'Memory Foam Pillow', 'Weighted Blanket'
]

unit_prices = [1200, 35, 120, 350, 90, 450, 800, 250, 180,
                25, 95, 110, 55, 180, 220, 65, 45, 85, 30, 70]

unit_costs  = [720, 15, 55, 175, 40, 200, 380, 110, 80,
                10, 42, 55, 24, 85, 110, 30, 18, 38, 12, 30]

colors = ['Silver', 'Black', 'White', 'Black', 'Black',
           'Gray',   'White', 'Walnut', 'Oak',
           'Blue',   'Indigo', 'Black', 'Black',
           'Yellow', 'Red',   'Silver',
           'Black',  'White', 'White', 'Gray']

specs = ['Intel i9, 32GB', 'Bluetooth 5.0', 'Cherry MX Blue', '4K IPS 144Hz', '1080p 60fps',
          'Lumbar Support', 'Height Adjustable', '5-Shelf', 'Solid Wood',
          '100% Cotton', 'Denim Blend', 'Mesh Upper', 'Polyester',
          '20V Max', '1800W 7.25"', '10-Piece',
          'PFOA-Free', '1200W', '100% Memory Foam', '15lb Glass Beads']

weights = [2.1, 0.1, 0.9, 6.5, 0.3, 18.0, 45.0, 32.0, 22.0,
            0.2, 0.8, 0.7, 0.3, 1.8, 3.2, 2.1, 1.5, 2.3, 0.6, 2.8]

dim_product = pd.DataFrame({
    'product_id'  : range(1, 21),
    'product_key' : [f'PROD-{str(i).zfill(3)}' for i in range(1, 21)],
    'product_name': product_names,
    'category'    : categories,
    'product_line': product_lines,
    'spec'        : specs,
    'color'       : colors,
    'unit_price'  : unit_prices,
    'unit_cost'   : unit_costs,
    'weight_kg'   : weights
})

dim_product.to_csv('data/dim_product.csv', index=False)
print('dim_product:', dim_product.shape)
dim_product.head(5)

dim_product: (20, 10)

,product_id,product_key,product_name,category,product_line,spec,color,unit_price,unit_cost,weight_kg
0,1,PROD-001,Laptop Pro 15,Electronics,Consumer Tech,"Intel i9, 32GB",Silver,1200,720,2.1
1,2,PROD-002,Wireless Mouse,Electronics,Consumer Tech,Bluetooth 5.0,Black,35,15,0.1
2,3,PROD-003,Mechanical Keyboard,Electronics,Consumer Tech,Cherry MX Blue,White,120,55,0.9
3,4,PROD-004,"Monitor 27""",Electronics,Professional,4K IPS 144Hz,Black,350,175,6.5
4,5,PROD-005,4K Webcam,Electronics,Professional,1080p 60fps,Black,90,40,0.3

## Fact Tables

In [8]:
# helper – map a date to its date_key
date_key_map = dict(zip(pd.to_datetime(dim_date['date']), dim_date['date_key']))

def random_date_keys(n, start='2019-01-01', end='2024-12-31'):
    """Return n random date_keys uniformly between start and end."""
    dates = pd.to_datetime(
        np.random.randint(
            pd.Timestamp(start).value,
            pd.Timestamp(end).value,
            size=n,
            dtype=np.int64
        )
    ).normalize()
    return dates.map(date_key_map).values

In [9]:
# ── fact_sales ─────────────────────────────────────────────────────────────────
n_sales = 100_000

product_ids  = np.random.choice(dim_product['product_id'].values,  size=n_sales)
customer_ids = np.random.choice(dim_customer['customer_id'].values, size=n_sales)
date_keys    = random_date_keys(n_sales)

price_map = dict(zip(dim_product['product_id'], dim_product['unit_price']))
cost_map  = dict(zip(dim_product['product_id'], dim_product['unit_cost']))

quantity_sold = np.random.randint(1, 51, size=n_sales)
unit_prices   = np.array([price_map[p] for p in product_ids])
unit_costs_s  = np.array([cost_map[p]  for p in product_ids])
discount_pct  = np.round(np.random.choice([0, 0, 0, 5, 10, 15, 20], size=n_sales).astype(float), 2)

gross_revenue  = quantity_sold * unit_prices
discount_amt   = np.round(gross_revenue * discount_pct / 100, 2)
net_revenue    = np.round(gross_revenue - discount_amt, 2)
total_cost_s   = quantity_sold * unit_costs_s
profit         = np.round(net_revenue - total_cost_s, 2)
profit_margin  = np.round(np.where(net_revenue > 0, profit / net_revenue * 100, 0), 2)

fact_sales = pd.DataFrame({
    'sales_id'         : range(1, n_sales + 1),
    'date_key'         : date_keys,
    'product_id'       : product_ids,
    'customer_id'      : customer_ids,
    'quantity_sold'    : quantity_sold,
    'unit_price'       : unit_prices,
    'discount_pct'     : discount_pct,
    'order_number'     : [f'ORD-{str(i).zfill(7)}' for i in range(1, n_sales + 1)],
    'discount_amount'  : discount_amt,
    'gross_revenue'    : gross_revenue,
    'net_revenue'      : net_revenue,
    'total_cost'       : total_cost_s,
    'profit'           : profit,
    'profit_margin_pct': profit_margin
})

fact_sales.to_csv('data/fact_sales.csv', index=False)
print('fact_sales:', fact_sales.shape)
fact_sales.head(3)

fact_sales: (100000, 14)

,sales_id,date_key,product_id,customer_id,quantity_sold,unit_price,discount_pct,order_number,discount_amount,gross_revenue,net_revenue,total_cost,profit,profit_margin_pct
0,1,1093,7,4,49,800,5.0,ORD-0000001,1960.0,39200,37240.0,18620,18620.0,50.00
1,2,1276,20,2,1,70,15.0,ORD-0000002,10.5,70,59.5,30,29.5,49.58
2,3,1314,15,2,49,220,15.0,ORD-0000003,1617.0,10780,9163.0,5390,3773.0,41.18

In [10]:
# ── fact_inventory ─────────────────────────────────────────────────────────────
n_inv = 8_000

fact_inventory = pd.DataFrame({
    'inventory_id'      : range(1, n_inv + 1),
    'date_key'          : random_date_keys(n_inv),
    'product_id'        : np.random.choice(dim_product['product_id'].values,  size=n_inv),
    'facility_id'       : np.random.choice(dim_facility['facility_id'].values, size=n_inv),
    'stock_level'       : np.random.randint(0,    2001, size=n_inv),
    'safety_stock_level': np.random.randint(50,   501,  size=n_inv),
    'reorder_point'     : np.random.randint(100,  601,  size=n_inv)
})

fact_inventory.to_csv('data/fact_inventory.csv', index=False)
print('fact_inventory:', fact_inventory.shape)
fact_inventory.head(3)

fact_inventory: (8000, 7)

,inventory_id,date_key,product_id,facility_id,stock_level,safety_stock_level,reorder_point
0,1,1115,17,4,1887,446,260
1,2,726,12,4,842,413,559
2,3,493,15,4,1956,445,111

In [11]:
# ── fact_procurement ───────────────────────────────────────────────────────────
n_proc = 3_000

order_date_keys = random_date_keys(n_proc, end='2024-11-30')
lead_times      = np.random.randint(5, 61, size=n_proc)

# compute delivery date_keys from order date + lead time
inv_date_key_map = {v: k for k, v in date_key_map.items()}
delivery_date_keys = []
for dk, lt in zip(order_date_keys, lead_times):
    delivery_dt = inv_date_key_map[dk] + timedelta(days=int(lt))
    delivery_dt = min(delivery_dt, datetime(2024, 12, 31))
    delivery_date_keys.append(date_key_map[delivery_dt])

proc_product_ids  = np.random.choice(dim_product['product_id'].values,   size=n_proc)
proc_supplier_ids = np.random.choice(dim_supplier['supplier_id'].values,  size=n_proc)
order_qty         = np.random.randint(50, 1001, size=n_proc)
proc_unit_costs   = np.array([cost_map[p] * np.random.uniform(0.85, 1.05) for p in proc_product_ids]).round(2)
total_cost_p      = np.round(order_qty * proc_unit_costs, 2)

fact_procurement = pd.DataFrame({
    'procurement_id'  : range(1, n_proc + 1),
    'order_date_key'  : order_date_keys,
    'product_id'      : proc_product_ids,
    'supplier_id'     : proc_supplier_ids,
    'order_quantity'  : order_qty,
    'unit_cost'       : proc_unit_costs,
    'lead_time_days'  : lead_times,
    'delivery_date_key': delivery_date_keys,
    'quality_score'   : np.round(np.random.uniform(3.0, 5.0, size=n_proc), 2),
    'po_number'       : [f'PO-{str(i).zfill(6)}' for i in range(1, n_proc + 1)],
    'total_cost'      : total_cost_p
})

fact_procurement.to_csv('data/fact_procurement.csv', index=False)
print('fact_procurement:', fact_procurement.shape)
fact_procurement.head(3)

fact_procurement: (3000, 11)

,procurement_id,order_date_key,product_id,supplier_id,order_quantity,unit_cost,lead_time_days,delivery_date_key,quality_score,po_number,total_cost
0,1,1442,10,10,115,9.01,30,1472,4.71,PO-000001,1036.15
1,2,341,18,4,581,35.52,13,354,4.68,PO-000002,20637.12
2,3,668,20,3,481,31.04,11,679,3.40,PO-000003,14930.24

In [12]:
# ── fact_production ────────────────────────────────────────────────────────────
n_prod = 9_000

qty_produced   = np.random.randint(100, 1001, size=n_prod)
defect_rate    = np.round(np.random.uniform(0.0, 0.05, size=n_prod), 4)
defective_units = np.round(qty_produced * defect_rate).astype(int)

fact_production = pd.DataFrame({
    'production_id'   : range(1, n_prod + 1),
    'date_key'        : random_date_keys(n_prod),
    'product_id'      : np.random.choice(dim_product['product_id'].values,  size=n_prod),
    'facility_id'     : np.random.choice(dim_facility['facility_id'].values, size=n_prod),
    'quantity_produced': qty_produced,
    'defective_units' : defective_units,
    'batch_number'    : [f'BATCH-{str(i).zfill(6)}' for i in range(1, n_prod + 1)],
    'defect_rate_pct' : np.round(defect_rate * 100, 2)
})

fact_production.to_csv('data/fact_production.csv', index=False)
print('fact_production:', fact_production.shape)
fact_production.head(3)

fact_production: (9000, 8)

,production_id,date_key,product_id,facility_id,quantity_produced,defective_units,batch_number,defect_rate_pct
0,1,1367,13,1,163,1,BATCH-000001,0.85
1,2,1104,16,1,522,15,BATCH-000002,2.83
2,3,274,8,1,648,20,BATCH-000003,3.08

In [13]:
# ── fact_shipment ──────────────────────────────────────────────────────────────
n_ship = 12_000

carriers      = ['FedEx', 'UPS', 'DHL', 'USPS', 'Amazon Logistics']
statuses      = ['Delivered', 'Delivered', 'Delivered', 'In Transit', 'Delayed', 'Returned']
delay_reasons = ['Weather', 'Customs', 'Carrier Delay', 'Address Issue', None, None, None]

ship_date_keys = random_date_keys(n_ship, end='2024-11-30')
transit_days   = np.random.randint(1, 15, size=n_ship)

delivery_date_keys_s = []
for dk, td in zip(ship_date_keys, transit_days):
    delivery_dt = inv_date_key_map[dk] + timedelta(days=int(td))
    delivery_dt = min(delivery_dt, datetime(2024, 12, 31))
    delivery_date_keys_s.append(date_key_map[delivery_dt])

ship_qty     = np.random.randint(1, 201, size=n_ship)
ship_prod_ids = np.random.choice(dim_product['product_id'].values, size=n_ship)
weight_map   = dict(zip(dim_product['product_id'], dim_product['weight_kg']))
total_weight = np.round(ship_qty * np.array([weight_map[p] for p in ship_prod_ids]), 2)

ship_statuses     = np.random.choice(statuses, size=n_ship)
ship_delay_reasons = [
    random.choice(delay_reasons[:-2]) if s == 'Delayed' else None
    for s in ship_statuses
]

fact_shipment = pd.DataFrame({
    'shipment_id'      : range(1, n_ship + 1),
    'ship_date_key'    : ship_date_keys,
    'delivery_date_key': delivery_date_keys_s,
    'product_id'       : ship_prod_ids,
    'facility_id'      : np.random.choice(dim_facility['facility_id'].values, size=n_ship),
    'customer_id'      : np.random.choice(dim_customer['customer_id'].values, size=n_ship),
    'quantity'         : ship_qty,
    'carrier'          : np.random.choice(carriers, size=n_ship),
    'status'           : ship_statuses,
    'shipping_cost'    : np.round(np.random.uniform(5, 500, size=n_ship), 2),
    'total_weight_kg'  : total_weight,
    'tracking_number'  : [f'TRK-{str(i).zfill(8)}' for i in range(1, n_ship + 1)],
    'delay_reason'     : ship_delay_reasons
})

fact_shipment.to_csv('data/fact_shipment.csv', index=False)
print('fact_shipment:', fact_shipment.shape)
fact_shipment.head(3)

fact_shipment: (12000, 13)

,shipment_id,ship_date_key,delivery_date_key,product_id,facility_id,customer_id,quantity,carrier,status,shipping_cost,total_weight_kg,tracking_number,delay_reason
0,1,1035,1042,2,3,5,6,FedEx,Delayed,113.16,0.6,TRK-00000001,Weather
1,2,527,530,17,3,1,117,FedEx,Delivered,7.94,175.5,TRK-00000002,None
2,3,2040,2048,18,1,5,20,UPS,Returned,459.22,46.0,TRK-00000003,None

## Verification – Reload All Tables

In [14]:
dim_customer     = pd.read_csv('data/dim_customer.csv')
dim_date         = pd.read_csv('data/dim_date.csv')
dim_facility     = pd.read_csv('data/dim_facility.csv')
dim_product      = pd.read_csv('data/dim_product.csv')
dim_supplier     = pd.read_csv('data/dim_supplier.csv')
fact_inventory   = pd.read_csv('data/fact_inventory.csv')
fact_procurement = pd.read_csv('data/fact_procurement.csv')
fact_production  = pd.read_csv('data/fact_production.csv')
fact_sales       = pd.read_csv('data/fact_sales.csv')
fact_shipment    = pd.read_csv('data/fact_shipment.csv')

tables = {
    'dim_customer'    : dim_customer,
    'dim_date'        : dim_date,
    'dim_facility'    : dim_facility,
    'dim_product'     : dim_product,
    'dim_supplier'    : dim_supplier,
    'fact_inventory'  : fact_inventory,
    'fact_procurement': fact_procurement,
    'fact_production' : fact_production,
    'fact_sales'      : fact_sales,
    'fact_shipment'   : fact_shipment,
}

for name, df in tables.items():
    print(f'{name:20s}  rows = {df.shape[0]:>7,}  cols = {df.shape[1]}')

dim_customer          rows =       5  cols = 7
dim_date              rows =   2,192  cols = 11
dim_facility          rows =       5  cols = 8
dim_product           rows =      20  cols = 10
dim_supplier          rows =      10  cols = 8
fact_inventory        rows =   8,000  cols = 7
fact_procurement      rows =   3,000  cols = 11
fact_production       rows =   9,000  cols = 8
fact_sales            rows = 100,000  cols = 14
fact_shipment         rows =  12,000  cols = 13